### ISSUE TITLE
ECS Agent disconnection

### ISSUE THREAD

**Issue by anosulchik** [aws/amazon-ecs-agent#250]
Hi, we're using ecs service from AWS and bootstrap instances by running ecs-agent docker container. In most cases it works well and ecs instance got registered. At the same time sometimes ecs agents stops working and ecs instance is shown as disconnected in ecs aws console. When it happens ecs-agent docker container is still running and we see the following errors in `docker logs ecs-agent`:

<pre>2015-11-11T12:09:56Z [INFO] Starting Agent: Amazon ECS Agent - v1.6.0 (34235e3)
2015-11-11T12:09:56Z [INFO] Loading configuration
2015-11-11T12:09:56Z [INFO] Checkpointing is enabled. Attempting to load state
2015-11-11T12:09:56Z [INFO] Loading state! module="statemanager"
2015-11-11T12:09:56Z [INFO] Detected Docker versions [1.17 1.18 1.19]
2015-11-11T12:09:56Z [INFO] Registering Instance with ECS
2015-11-11T12:09:56Z [INFO] Registered! module="api client"
2015-11-11T12:09:56Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:us-east-1:373682980683:container-instance/bb44e8da-f404-43c2-84b0-91871286d84d' in cluster 'anosulchik3-ECSCluster-2HS41EBPRSLK'
2015-11-11T12:09:56Z [INFO] Saving state! module="statemanager"
2015-11-11T12:09:56Z [INFO] Beginning Polling for updates
2015-11-11T12:09:56Z [INFO] Initializing stats engine module="stats"
2015-11-11T12:09:56Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-11-11T12:09:56Z [INFO] Creating poll dialer module="ws client" host="ecs-t-2.us-east-1.amazonaws.com"
2015-11-11T12:10:06Z [INFO] Saving state! module="statemanager"
2015-11-11T12:19:12Z [WARN] ACS Connection hasn't had any activity for too long; closing connection module="acs handler"
2015-11-11T12:19:12Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.18.202:443: use of closed network connection"
2015-11-11T12:19:12Z [INFO] Error from acs; backing off module="acs handler" err="read tcp 54.239.18.202:443: use of closed network connection"
2015-11-11T12:19:32Z [ERROR] Unable to discover poll endpoint module="acs handler" err="RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: net/http: request canceled while waiting for connection"
2015-11-11T12:19:32Z [INFO] Error from acs; backing off module="acs handler" err="RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: net/http: request canceled while waiting for connection"
2015-11-11T12:19:53Z [ERROR] Unable to discover poll endpoint module="acs handler" err="RequestError: send request failed
...</pre>

As you can see ecs agent worked for 10 minutes when it started throwing errors and deregiestered from ecs.

Please advise.

**Comment by buley** [comment]
Related to #219

**Comment by samuelkarp** [comment]
@anosulchik Can you get logs at the debug level for both the ECS Agent and the Docker daemon?  Does the Agent stay disconnected forever or does it eventually reconnect?

**Comment by anosulchik** [comment]
@samuelkarp Unfortunately I don't have debug level logs from ecs agent at time when it disconnected. At the same time I've just retrieved INFO logs from instance that was affected by ecs agent disconnection (it happened at Dec 12, 2015 at 13:21:18.902 UTC), please see the log attached.
[Uploading ecs-agent.txt…]()

Let me confirm that ecs agent remains disconnected. Restart of ecs agent container and/or docker doesn't help so we need to reinstall docker with fresh ecs agent container.

**Comment by samuelkarp** [comment]
@anosulchik The logs you provided appear to only have data for December 7.  Can you gather logs at the debug level when this happens again?  Those logs (from both the ECS Agent and Docker daemon) will be very helpful in figuring out what is going wrong.  Additionally, can you tell me the following information:

* Which Docker version are you using?
* Which operating system are you using?
* Are you using a Docker daemon packaged by the operating system vendor or by the Docker project?
* What options are you using when launching the Docker daemon?
* What is the output of `docker inspect ecs-agent`? (Please remove any credentials that appear in that output)

**Comment by mkabischev** [comment]
I`ve got the same problem with agent 1.7.1 on instances launched in private subnet. Also i`ve got few instances in public subnet and everything works well. What kind of information do you need?

**Comment by samuelkarp** [comment]
@mkabischev Do your instances have a route to the internet via an IGW, NAT, or proxy?

**Comment by mkabischev** [comment]
@samuelkarp, they`re sitting behind NAT.

**Comment by samuelkarp** [comment]
@mkabischev Are you seeing the same log lines as @anosulchik or something different?

**Comment by LukePeterson** [comment]
Also experiencing this error after upgrading to the agent to v1.8.0.  What can I do to help?

**Comment by gregwebs** [comment]
When I run ~2000 tasks on ~400 instances I see this problem multiple times an hour. My recourse right now is to terminate the instance, but that is a very slow and expensive solution.

```
2016-02-23T23:06:41Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:06:41Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:06:41Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:06:42Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:07:06Z [INFO] Creating poll dialer module="ws client" host="ecs-t-2.us-east-1.amazonaws.com"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:bc30b743e257e735f1893a522d350c2f1ba3b3d66e1be059b324d880f6c13c55}"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:6b90e0f2f83f0c0e637ca62eeaa0db5486441efe9326727a4bf542661ba9cc1b}"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:da5105a670fd4054a0b192a5dfd75e3d823062c8ac0db179e4809179771c4c05}"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:1495c5d4c2c61a3b1a58cef7be97e472696cc7b45ddd832355c1f0a8e3464c0a}"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:06a7c13436fd71074ccbe8019d76e006e32ce47446a51b3b3c65ac226e1be979}"
2016-02-23T23:07:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:6ee0508d66485a4a0d881200045a5205c27aeff48bcd930c612707c10a17ba7d}"
2016-02-23T23:07:06Z [WARN] Error getting instance metrics module="tcs client" err="No task metrics to report"
2016-02-23T23:09:39Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:09:39Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:09:39Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:09:39Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:11:40Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:11:40Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:11:40Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:11:41Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:13:42Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:13:42Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:13:42Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:13:43Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:17:26Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:17:26Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:17:26Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:17:26Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:21:06Z [INFO] Creating poll dialer module="ws client" host="ecs-t-2.us-east-1.amazonaws.com"
2016-02-23T23:21:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:06a7c13436fd71074ccbe8019d76e006e32ce47446a51b3b3c65ac226e1be979}"
2016-02-23T23:21:06Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:6ee0508d66485a4a0d881200045a5205c27aeff48bcd930c612707c10a17ba7d}"
2016-02-23T23:21:06Z [WARN] Error getting instance metrics module="tcs client" err="No task metrics to report"
2016-02-23T23:21:13Z [INFO] No handler for message type module="ws client" type="CloseMessage"
2016-02-23T23:21:13Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
2016-02-23T23:21:13Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
2016-02-23T23:21:13Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2016-02-23T23:28:55Z [WARN] ACS Connection hasn't had any activity for too long; closing connection module="acs handler"
```

**Comment by jpignata** [comment]
We just found two of our instances with agents disconnected and have these errors in the logs:

```
ecs-agent.log.2016-02-23-08:2016-02-23T08:31:50Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-08:2016-02-23T08:31:50Z [INFO] Error from tcs; backing off module="tcs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-13:2016-02-23T13:45:05Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-13:2016-02-23T13:45:05Z [INFO] Error from tcs; backing off module="tcs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-19:2016-02-23T19:15:08Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-19:2016-02-23T19:15:08Z [INFO] Error from tcs; backing off module="tcs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:18:35Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:18:35Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:18:35Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:21:08Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:21:08Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:21:08Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:24:43Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:24:43Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:24:43Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:26:46Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:26:46Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:26:46Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:28:47Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:28:47Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:28:47Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:30:49Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:30:49Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:30:49Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:32:50Z [INFO] No handler for message type module="ws client" type="CloseMessage"
ecs-agent.log.2016-02-23-23:2016-02-23T23:32:50Z [ERROR] Error getting message from ws backend module="ws client" err="unexpected EOF"
ecs-agent.log.2016-02-23-23:2016-02-23T23:32:50Z [INFO] Error from acs; backing off module="acs handler" err="unexpected EOF"
```

We're running 1.8.0 on the latest ECS optimized Amazon Linux. I can't say for sure, but I suspect this started with the upgrade to 1.8.0.

**Comment by gregwebs** [comment]
Pretty sure I have seen this problem pre 1.8.0. It may have gotten worse post 1.8.0

**Comment by jpignata** [comment]
Looks like my issue is related to https://github.com/aws/amazon-ecs-agent/issues/316 and possibly fixed in the next release.

**Comment by gregwebs** [comment]
I can confirm things got much, much worse with 1.8.0. I just down-graded and I don't see the issue (it probably still happens, but much less frequently).

**Comment by ChrisRut** [comment]
Can this be closed as a dupe of https://github.com/aws/amazon-ecs-agent/issues/313#issuecomment-187003013 ?

**Comment by aaithal** [comment]
As stated in #313: "Fixing this deadlock issue has been released as part of Agent v1.8.1. We also released a new AMI with the v1.8.1 agent bundled.

If you continue to run into issues or have new information, please do reopen this or a new issue."
