### ISSUE TITLE
ECS agent opens too many connections to Docker via /var/run/docker.sock

### ISSUE THREAD

**Issue by anosulchik** [aws/amazon-ecs-agent#517]
Hi, we faced the problem with too many socket connections to Docker (/var/run/docker.sock) on latest ECS optimized AMI ami-6bb2d67c. We upgraded to it once got message from Amazon quoted below. But we hit exactly the same problem that supposed to be fixed in that AMI.

> According to our records, you are currently running or you have recently launched an Amazon ECS-optimized AMI where the agent may open too many socket connections to Docker, which can exhaust the limit of Docker socket connections and make the agent unable to start new tasks (agent versions 1.11.1 and 1.12.0).
> 
> We recommend that you update to the latest agent [1] or update to the latest Amazon ECS-optimized AMI

Too many opened connections to docker:

```
[root@ip-172-31-25-188 ~]# netstat -x | grep '/var/run/docker.sock' | wc -l
930

[root@ip-172-31-25-188 ~]# netstat -x | grep '/var/run/docker.sock' | head -3
unix  3      [ ]         STREAM     CONNECTED     685428 /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     683558 /var/run/docker.sock
unix  2      [ ]         STREAM     CONNECTED     529461 /var/run/docker.sock
```

As soon as it happens `docker ps` hangs but containers seems to be continue running but ECS agent can't stop/start new ones anymore since it hangs too so those tasks get stuck in PENDING state:

```
[root@ip-172-31-25-188 ~]# curl 127.0.0.1:51678/v1/tasks
{"Tasks":[{"Arn":"arn:aws:ecs:us-east-1:000:task/cd562f5f-2dbb-45e6-818f-138ce28176f9","DesiredStatus":"STOPPED","KnownStatus":"RUNNING","Family":"tf-strings-search-service-prod","Version":"84","Containers":[{"DockerId":"e71a83367120f9727c1bc631be4fd60080c12ea8b18d5454c9772fb1b2896e3d","DockerName":"ecs-tf-strings-search-service-prod-84-logstashshipper-fab2888deceac0804c00","Name":"logstashshipper"},{"DockerId":"18755b2eeaec7a215f4f6beff296e15216c1fc36ed6ee3204fa60d2e711e827e","DockerName":"ecs-tf-strings-search-service-prod-84-search-service-86d780fce4b1eea56700","Name":"search-service"}]},{"Arn":"arn:aws:ecs:us-east-1:000:task/9d602625-3285-4b59-8105-38742aaf8f08","DesiredStatus":"RUNNING","KnownStatus":"PENDING","Family":"tf-strings-search-service-prod","Version":"85","Containers":[]}]}
```

Please see my comment in another ticket that contains more debugging data like ECS agent stack dump: https://github.com/aws/amazon-ecs-agent/issues/515#issuecomment-244331856

**Comment by kiranmeduri** [comment]
Hi @anosulchik, can you give us more detail on 
- how may containers are running on this host?
- are all the containers managed by ECS agent?

Agent opens a connection for every container managed by it. So the number of open connections should be 1:1 with the number of containers. Are you seeing any connection leak?

Thanks

**Comment by anosulchik** [comment]
> how may containers are running on this host?
There are three containers: ecs-agent and two containers with java applications. You can see task definition here https://gist.github.com/anosulchik/29312f8b30fa6f88b9c997281d32d822

> are all the containers managed by ECS agent?
Yes, ecs-agent manages containers with java mentioned above.

**Comment by anosulchik** [comment]
> Are you seeing any connection leak?
Yes, there's much more connections e.g. hundred or thousands.

**Comment by kiranmeduri** [comment]
can you share the following details via email to meduri (at) amazon.com

- AWS region
- ECS cluster
- EC2 instanceId (or) ECS Container InstanceId

Thanks

**Comment by kiranmeduri** [comment]
Along with them please share the following too (if available)

- docker daemon logs
- agent logs
- repro steps (if any). Unfortunately I tried running few instances with many containers and did not see the same behavior. So I am certainly missing something.

Thanks

**Comment by anosulchik** [comment]
@kiranmeduri I've sent you details about affected EC2 instance to email per your request. Please see further troubleshooting information below:

Docker logs: https://www.wetransfer.com/downloads/58cc1d9396aa5fa4ee76e3f8c5c5bb2720160906083354/13ae05be132e9f2f5d6bd9f4f3130a0a20160906083354/6b82e6

ECS agent logs: https://www.wetransfer.com/downloads/c2f2a68373a8527a0986b49cd4b91fd320160906082455/4603a041d10ff4cd33bd910ace3735e220160906082455/3da3c5

Unfortunately there's no clear rerpo steps, at least I can't find anything that could 100% trigger this problem.

**Comment by perhallstroem** [comment]
For what it is worth, I am also seeing this problem. We also run a large number of relatively short-lived tasks, and after about an hour we have 1014 exited containers. There seems to be 1016 sockets open:
```
# netstat -x | grep '/var/run/docker.sock' | wc -l
1016
```

Is it expected that a socket is open even for *exited* containers? I appear to be able to recover by manually deleting the containers and (possibly) killing the agent.

**Comment by aaithal** [comment]
@perhallstroem @anosulchik an update here. We have fixed a bug in the latest release of the ECS Agent where it could miss cleaning up its `Stats` connection with docker leading to the behavior that you have reported here. Could you please let us know if you keep running into this issue on the [latest ECS Agent](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.12.2)?

**Comment by anosulchik** [comment]
@aaithal Thank you for your update. I've tried latest ECS optimized AMI ami-3d55272a that comes with latest ECS agent pre-installed. Unfortunately the problem still reproduces -- docker hangs after a few days running at new EC2 instances, there were hundreds of opened file socket connections to it.

**Comment by aignas** [comment]
I just wanted to add that I could also reproduce the issue, but in a slightly different way.
One of our tasks was restarting a lot and what I noticed is that the log for `ecs-agent` container grew to 12GB and it conained a lot of messages like:

```
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.749786786Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.749810745Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.749820217Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.749928532Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.749991395Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750002276Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750004322Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750091439Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750111356Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750141029Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750144101Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.7502255Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750225565Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750285034Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750285017Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750318551Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750311271Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750385447Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750431923Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750528683Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750539513Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750506781Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750558051Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.75060056Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750642446Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750735252Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750735151Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750830807Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750832081Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.750957028Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.750957184Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751022329Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751022014Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751080978Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751080981Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751164126Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751164099Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751230649Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751248346Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.75134362Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751363639Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751442846Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751462263Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751548362Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.75156644Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751572137Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751588925Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751609464Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751623386Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751722817Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751735465Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751849196Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751858635Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751905021Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751913268Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751930695Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.751942371Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.751985018Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752002772Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752102256Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752102117Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752120825Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.75224682Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752259367Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752270556Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752293675Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752263464Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752385575Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752401185Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.75241284Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752432072Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752478564Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752485874Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752618529Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752634398Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752688981Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752698571Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752794414Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752795311Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752812768Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752854242Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.752957885Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.752958615Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753062582Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.753069204Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.75309292Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753099976Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753220579Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.753234286Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container cb8b3d9d7476027954510e27c9f15d69c966a2c77780f4193bdcf13c35b2c255: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753306674Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.753324444Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753345699Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.753386453Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 7e99e4a80784a006aba54a43d76bce75db44202deaaabb576db7bf0c27d5dc3a: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753501613Z"}
{"log":"Seelog error: invalid argument\n","stream":"stderr","time":"2016-09-24T05:45:28.753511992Z"}
{"log":"2016-09-24T05:45:28Z [WARN] Error retrieving stats for container 2b69dc2484852c5de6fc18ea92d3a65e95ee2a39d6efa43dd35ad1094b4c1b70: dial unix /var/run/docker.sock: socket: too many open files\n","stream":"stdout","time":"2016-09-24T05:45:28.753531604Z"}
```

I was using `amzn-ami-2016.03.g-amazon-ecs-optimized-4ce33fd9-63ff-4f35-8d3a-939b641f1931-ami-52cd5445.3 (ami-00522773)`

**Comment by richardpen** [comment]
@aignas @anosulchik @perhallstroem We have found a possible reason that could cause this error and currently are working on a fix, will let you know when we have an update.

**Comment by aaithal** [comment]
@aignas @anosulchik @perhallstroem Most of the issues with `too many open file descriptors` had to do with the fact that when docker gets slow or if any request to docker times out from the Agent's perspective, the connections would linger and when such connections accumulate over time, the `too many open file descriptors` error would surface. This should be fixed when the PR #544 gets merged and released. 

Thanks,
Anirudh

**Comment by kaihendry** [comment]
I think I ran into this issue on **1.11.1** and then the Agent IIUC brought down the instance by filling the disk with logs:
https://static.spuul.com/devops/2016-10-25/ecs-agent-log.tar.xz

If it should be another issue, please let me know. Have a number of issues in production I'm trying to get answers for: https://devops.spuul.com/2016-10-25/ECS_downtime/

**Comment by richardpen** [comment]
@kaihendry This is the same issue here. The reason cause this may be low I/O credits of the instance, which cause the docker response very "slow". For the scaling issue in your list, does [auto scaling group](https://aws.amazon.com/blogs/compute/scaling-amazon-ecs-services-automatically-using-amazon-cloudwatch-and-aws-lambda/) fits your use case?

**Comment by richardpen** [comment]
@kaihendry After taking a look at the logs, I think this is the same issue as reported above. 
Also in the logs there are a lot of errors with collecting metrics for container:
```
2016-10-24T23:00:00Z [WARN] Error retrieving stats for container be34eb9c592dab4270e848184e5bb8297dd80eb69d9035547b77627581c7287a: dial unix /var/run/docker.sock: socket: too many open files
```
This issue has been fixed in [v1.12.2](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.12.2). Update the agent to the latest version should get rid of these error logs. For the scaling issue in your list, does something like [auto scaling group](https://aws.amazon.com/blogs/compute/scaling-amazon-ecs-services-automatically-using-amazon-cloudwatch-and-aws-lambda/) fit your use case?

**Comment by richardpen** [comment]
@aignas @anosulchik @perhallstroem We have released [v1.13.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.13.1) today, the fix is available in the latest version. I'm closing this now, feel free to reopen it if you run into the issue in the future.
